name: Run test

on:
  pull_request:
    branches:
      - main

jobs:
  restrict_pr_sources:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        id: source_check
        run: |
          echo "Source branch is: ${{ github.head_ref }}"
          # Allow only branches matching release/<major>.<minor>.<patch>
          if [[ "${{ github.head_ref }}" =~ ^release/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "✅ Pull request source is a valid release branch."
          else
            echo "::error::❌ PRs to main are only allowed from release/x.y.z branches (e.g., release/1.2.3). Got: ${{ github.head_ref }}"
            exit 1
          fi

  run-tests:
    needs: restrict_pr_sources
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', '**/gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execution permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testDebug