name: Deploy To Google Play

on:
  push:
    branches:
      - main

jobs:
 test:
   name: Unit Test
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v4

     - name: Setup JDK 17
       uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: 17
         cache: 'gradle'

     - name: Grant execution permission for gradlew
       run: chmod +x gradlew

     - name: Run unit tests
       run: ./gradlew clean testDebug

 distribute:
   name: Distribute bundle to Google Play
   needs: test
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v4

     - name: Setup JDK 17
       uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: 17
         cache: 'gradle'

     - name: Version Bump
       uses: chkfung/android-version-actions@v1.2.3
       with:
         gradlePath: app/build.gradle.kts
         versionCode: ${{ github.run_number }}

     - name: Assemble Release Bundle
       run: ./gradlew bundleRelease

     - name: Sign Release
       uses: r0adkll/sign-android-release@v1
       with:
         releaseDirectory: app/build/outputs/bundle/release
         signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
         keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
         alias: ${{ secrets.KEY_ALIAS }}
         keyPassword: ${{ secrets.KEY_PASSWORD }}

     - name: Setup Authorization with Google Play Store
       run: echo '${{ secrets.GOOGLE_PLAY_AUTH_JSON }}' > service_account.json

     - name: Deploy Bundle to Google Play
       uses: r0adkll/upload-google-play@v1.1.3
       with:
         serviceAccountJson: service_account.json
         packageName: com.tibadev.alimansour.prophetstories
         releaseFiles: app/build/outputs/bundle/release/app-release.aab
         track: internal
         inAppUpdatePriority: 5
         status: completed